#!/usr/bin/env node

const bytes = require('bytes')

const { argv } = require('yargs')
  .usage('usage: ./$0 <source id> <target id> [options]\ntarget id optional，If not filled, use DEFAULT_TARGET in config.js')
  .alias('u', 'update')
  .describe('u', 'Do not use local cache, force to obtain source folder information from online')
  .alias('f', 'file')
  .describe('f', 'Copy a single file')
  .alias('n', 'name')
  .describe('n', 'Rename the target folder, keep the original directory name if not filled in')
  .alias('N', 'not_teamdrive')
  .describe('N', 'If it is not a team disk link, you can add this parameter to improve the interface query efficiency and reduce latency')
  .alias('s', 'size')
  .describe('s', 'Do not fill in the default copy all files, if this value is set, then filter out files smaller than this size, must end with b, such as 10mb')
  .alias('S', 'service_account')
  .describe('S', 'Specify to use the service account for operation, provided that the json authorization file must be placed in the ./sa directory. Please make sure that the sa account has operation permissions.')
  .help('h')
  .alias('h', 'help')

const { copy, copy_file, validate_fid } = require('./src/gd')
const { DEFAULT_TARGET } = require('./config')

let [source, target] = argv._

if (validate_fid(source)) {
  const { name, update, file, not_teamdrive, size, service_account } = argv
  if (file) {
    target = target || DEFAULT_TARGET
    if (!validate_fid(target)) throw new Error('The target id format is incorrect')
    return copy_file(source, target).then(r => {
      const link = 'https://drive.google.com/drive/folders/' + target
      console.log('The task is completed, the location of the file：\n', link)
    }).catch(console.error)
  }
  let min_size
  if (size) {
    console.log(`Do not copy files with a size less than ${size}`)
    min_size = bytes.parse(size)
  }
  copy({ source, target, name, min_size, update, not_teamdrive, service_account }).then(folder => {
    if (!folder) return
    const link = 'https://drive.google.com/drive/folders/' + folder.id
    console.log('\nTask completed, new folder link：\n', link)
  })
} else {
  console.warn('Directory ID is missing or malformed')
}
